### ISSUE TITLE
ext2 doesn't compile

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#105]
There seems to be something wrong with the wrapper file (or maybe the version of kernel). I tried several versions of linux kernels but none of them worked.

**Comment by ajaysusarla** [comment]
The commit 6bb9d91b9e1c1c7773c93f4c374065ef1659f07c should fix this.

**Comment by zilinc** [comment]
thanks a lot :)

**Comment by ajaysusarla** [comment]
No worries @zilinc
