### ISSUE TITLE
What and Why in README

### ISSUE THREAD

**Issue by craigem** [NICTA/cogent#2]
The README is excellent for installation and so on but lacks description of what Cogent does and why I would want it. 

The project was referred to me as:

"This is NICTA/Data61's new language for writing systems code that from a high level DSL generates both efficient run time code and a proof of correctness that can be checked by the Isobelle theorem prover.﻿"

I was unable to glean that from the README but the problem may also just be me :-)

Thanks!

**Comment by wom-bat** [comment]
Sure -- we put this up primarily for people who already know what cogent is (from the ASPLOS paper for example).  I agree it'd be nice to have a better README.

**Comment by zilinc** [comment]
@craigem That's indeed what I planned to do on Monday but didn't find time for. Thanks for the ticket and you can expect it to be there soon (I guess tomorrow should be practical).

**Comment by zilinc** [comment]
Added a link to the project homepage. Far from complete but should hopefully give you @craigem some idea. Hope more papers will appear there soon. Close this ticket for now. We'll keep updating.
