### ISSUE TITLE
local variable shadowing

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#224]
In the following program:
```
foo : (A -> B, A) -> B
foo (f, x) = f x

-- f : A -> B
```
If the `f` function is defined, then `foo` uses this global `f` instead of the local `f`.

**Comment by ajaysusarla** [comment]
Is this by design?

**Comment by ajaysusarla** [comment]
Sorry, ignore me, I just saw that it has been tagged a 'bug'

**Comment by zilinc** [comment]
The reason, partly, is that the dispatch function can only call top-level functions. So it errs on the global function side. But it's confusing. To see the details, just compile the above program without the commented-out line, and the C code is not correct.
