### ISSUE TITLE
record fields get permuted in solver

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#25]

**Comment by liamoc** [comment]
Is this a fundamental issue? Can't we just sort record fields before generating embeddings?

**Comment by zilinc** [comment]
haven't quite worked out where is the bug. but very likely a `fromList` or so.

**Comment by liamoc** [comment]
I think this will have to be fixed in a couple of other places as well.

**Comment by zilinc** [comment]
both reverted by cd2d0f642. need a different fix

**Comment by zilinc** [comment]
With this fix, because it's taking the `union` of the two lists of fields, in the `F/T` case, given the fields of the `F` is a subset of that of `T`, we can determine an order; in the `F/F` case, we cannot; and `T/T` we don't need.

**Comment by liamoc** [comment]
Yup, makes sense.
