### ISSUE TITLE
partial records not solved correctly

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#26]

**Comment by liamoc** [comment]
Can you elaborate on what's going on here?

**Comment by zilinc** [comment]
I haven't had a chance to trace the internals yet. In the ext2 case, it reports something like `{ a, b } take b` doesn't match `{b} take b`, which is basically a put followed by a take. I conjectured the cause to be F records related issues.

**Comment by zilinc** [comment]
THis is a regression due to the #25 fix

**Comment by zilinc** [comment]
The example wasn't well constructed. Please ignore.
