### ISSUE TITLE
Parser does not support cpphs #line directives

### ISSUE THREAD

**Issue by gteege** [NICTA/cogent#279]
The Cogent compiler uses cpphs as preprocessor but the parser does not support the #line directives created by cpphs. Therefore #line directive generation by cpphs is disabled. When using #include that causes wrong line numbers in error messages.
Cogent programs normally use the native include statement instead of the cpphs #include so that the problem does not occur. However, cpphs is applied separately to every file included this way. This implies that cpphs macros defined in an included file can only be used in the same file and not elsewhere in the Cogent program.
Is there any other reason for having a native Cogent include statement? Otherwise I propose to extend the parser by processing #line directives and use cpphs #include instead.

**Comment by gteege** [comment]
I implemented a parser extension and created a pull request.

**Comment by zilinc** [comment]
See #280.
