### ISSUE TITLE
Int and Bool

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#285]
Occasionally an integer can be typed as `Bool`.

For example:
```
c : Bool
c = 1
```
typechecks.

I think the root cause is in `==` and `/=`, which are polymorphic. The constraint generated is `integral alpha`, where `alpha` is the type of the operands.

**Comment by ajaysusarla** [comment]
But isn't that the way we've actually implemented it? Unlike other types, I always see `Bool` not represented as a tagged union.

**Comment by zilinc** [comment]
It doesn't matter how `Bool` is implemented. An Int shouldn't be allowed to be typed `Bool`. It's a bug in the typechecker.
