### ISSUE TITLE
'impossible' happened for lambda expression: bound not comparable

### ISSUE THREAD

**Issue by gteege** [NICTA/cogent#298]
The following code 

```
type A
type G a 
type R = { f1 : (G A)! }
f : R -> R
f r =
  let t = (\s => if True then s else s) r
  in if True then t else t
```

causes the error message:

```
Parsing...
Resolving dependencies...
Typechecking...
Desugaring and typing...
cogent: bound: not comparable: (TCon "A" [] (Boxed True (Bits {allocSize = 0, allocOffset = 0})),TCon "A" [] (Boxed False (Bits {allocSize = 0, allocOffset = 0}))): the 'impossible' happened!
If you see this, please report this bug to
    <https://github.com/NICTA/cogent/issues>

```
The error disappears when one of the conditions is simplified, or when the lambda expression is replaced by a seperate toplevel defined function.

**Comment by vjackson725** [comment]
Here's a simplified test case which also causes the issue.
```
type A
type G a 

f : (G A)! -> (G A)!
f r = (\s => s) r
```

The issue is roughly caused because the core type inference infers the type `(G A)! -> (G A)!` for the function, but the argument has the type `(G A!)!`.
