### ISSUE TITLE
Bang function types

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#30]
In the old compiler, `(A->B)! == A -> B`, and now `(A->B)! == A! -> B!`. Which is more appropriate?

**Comment by zilinc** [comment]
It breaks quite a bit of current code.

**Comment by liamoc** [comment]
Oh good point. I think that the old compiler is more correct.

**Comment by liamoc** [comment]
Fixed in my latest push.

**Comment by zilinc** [comment]
Thanks. Now that the ext2 errors become sensible (and fixable).
