### ISSUE TITLE
Cogent translates to exponentially larger C code

### ISSUE THREAD

**Issue by gteege** [NICTA/cogent#303]
Example:
```
f: U32 -> U32
f n =
   let a = if n < 5 then 10 else 3
   and b = if a < 6 then 9 else 4
   in a+b
```
Every line with a binding ``= if`` doubles the number of occurrences of the translated expression after ``in``. This is unexpected for the programmer.
It can be avoided by wrapping the conditional expression in a lambda term:
```
f: U32 -> U32
f n =
   let a = (\n => if n < 5 then 10 else 3) n
   and b = (\a => if a < 6 then 9 else 4) a
   in a+b
```

**Comment by zilinc** [comment]
It's not a bug. The duplication is due to how A-normal form is defined. K-normal form was introduced specifically for (partially) solving this problem. Use `--fnormalisation=knf` flag when compiling the code.

Also see #197

**Comment by gteege** [comment]
Ok, it works.
Are there any drawbacks for the refinement proof when using K-normal form?

Regards
Gunnar Teege

Am 08.10.19 um 01:19 schrieb Zilin Chen:

**Comment by zilinc** [comment]
There shouldn't be any major difference, seeing that BilbyFS was verified using KNF.
