### ISSUE TITLE
Numeric types are compatible with Bool.

### ISSUE THREAD

**Issue by gteege** [NICTA/cogent#312]
The code
```
f: Bool -> ()
f b = ()

g: () -> ()
g () = f 100000
```
compiles successfully.
If this is intended as an implicit type conversion from numeric to Bool,
you have a problem in Dargent: when specifying a layout size of 1b for 
a field of type Bool, a put numeric value will simply be masked to the least significant bit.
This will convert all even values to false and all odd values to true.

**Comment by zilinc** [comment]
Emmm, that's a good observation. We'll fix it. Thank you.

**Comment by zilinc** [comment]
Related: #285
