### ISSUE TITLE
Record Field (Non-)Reordering

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#333]
Description
--------------------------------------
The confusion and controversy around whether record field permutation should be allowed have been around since the very beginning of Cogent. If we had two record types `{ f : A, g : B }` and `{ g : B, f : A }`, should we treat them as the same? If we did, then we had to reorder the fields of the records in a consistent way, e.g. lexicographical order on field names. Reordering fields affects C code generation, and the FFI with native C. Traditionally, Cogent chooses a C struct which "naturally" match a Cogent record. In the example above, the C type will be `struct t1 { A f; B g; };` for the first type, and also for the second if we chose to reorder fields.

The introduction of Dargent changes the picture quite a bit. Because Dargent is designed to be a language for specifying how to represent Cogent datatypes in C, a Cogent type no longer maps to a single C type; it can be represented in many different ways, depending on the Dargent annotation. Because Dargent layout is on the bit and byte level, the generated C type for a Cogent record becomes a single array, wrapped by a struct to make it distinct from other structs of such. For example, the C type for the above Cogent type will be `struct t1 { char* thing; };` and `struct t2 { char* thing; };` respectively (note that only the name of the struct is different).

The Debate
--------------------------------------
* Reorder fields (current implementation): Cogent types should be layout neutral, meaning that the user should never rely on the Cogent type for its C definitions (or data layout in storage). Every time a Cogent type needs to interface with external C programs, it needs to be annotated with a Dargent layout. For the rest (internally used Cogent types), the Cogent compiler is free to choose any code generation mechanism and the choice is totally transparent to the users. We refer to this compiler-chosen layout the _default layout_.

* Don't reorder fields: Systems programmers tend to like the idea of "what you write is what you get", thus wanting to have control on the Cogent level. If a Cogent type naturally map to a C type (for example, point-wise map a Cogent record to a struct in C), the Dargent layout annotation shouldn't be mandatory. We refer to this layout mechanism _natural layout_, to differentiate itself with the default layout that the Cogent compiler chooses. Moreover, there's no way that using Dargent, a programmer can get a natural layout, as it will always be represented in C as a singleton struct with a byte array. Using Cogent types for natural layout avoids the need for a different Dargent syntax to layout a Cogent record as a regular C struct.

Plan
--------------------------------------
We decide to implement the no-reordering idea. It requires fair bit of changes to the compiler, in particular its surface typechecker. The current surface TC is implemented in a way that relies on reordering. To be more precise, when we infer record types, the concept of a _row_ is introduced. A row is essentially a set of fields that we know a record has, and optionally a row variable, representing all the rest fields that should be present but we don't yet know. Then by subtyping relations we can resolve the row variables to a concrete set of fields. A row, being a set, doesn't know in what order the fields should be inserted, thus losing order information.

Other than the surface typechecker, other parts of the compiler will need to change accordingly, but they are rather minor and are straightforward. The verification tool chain needs to change as well to reflect this. 

Related Ticket
--------------------------------------
#291 #313 

*Note*: The information in this ticket is mostly based on a meeting that we had recently (16/12/19); I tried my best to remember all the details, but there might be mistakes or omissions. Please fix them if you see anything wrong or missing.

**Comment by heb1001** [comment]
I think there are 3 layouts you’d normally want:

1) C native layout for C FFI.  Needs to be compatible with everything else
running locally.

2) Local internal layout optimized for performance, not used on any
interfaces so the compiler can do what it likes for performance.  C
programmers do this by hand by rearranging fields into cache lines and
specifying alignments and spacing out to avoid false sharing etc.

3) Exact binary layout with endianness specified for each field and lots of
bit-twiddling.  Must be portable across platforms.  This is for things like
device drivers where there is a memory mapped interface and hardware that
is used in multiple platforms with different architectures or for
networking where the packet formats have a specific layout.

I understand your summary below to mean that your plan addresses 1) with
natural layout and 3) with Dargent but you have sacrificed 2).

It would be good if you could make all of 1, 2 and 3 easy with minimal
coding overhead.  Profile directed feedback for 2 would get you bonus
points.

I haven’t really been following your work too closely recently so apologies
if this email is redundant.

**Comment by zilinc** [comment]
@heb1001 Thank you very much for your comment. You're absolutely right. The proposed plan basically unifies 2 with 1, based on the assumption that the natural layout is good enough in terms of performance. Of course this assumption is not valid, but for now I would go with this (false) assumption, as more sophisticated internal encoding means that we need more complicated Cogent-C refinement proofs, which is not a thing that can happen any time soon as far as I can tell. Going forward, when we want to separate 1 and 2, we can still do so by adding some lightweight syntax, differentiating 1 and 2.
