### ISSUE TITLE
new typechecker performance

### ISSUE THREAD

**Issue by liamoc** [NICTA/cogent#35]
We can solve a lot of performance problems by:

- [x] Coalescing equal constraints rather than LUBing/GLBing them.
- [ ] (Possibly) applying substitutions to fixed point in the substitutions themselves (not sure if this is a win)
- [ ] other things?

**Comment by liamoc** [comment]
OK, I've pushed to my local branch a patch that coalesces equal constraints. The downside is it will do a lot of comparisons to remove equal constraints at every phase of the typechecking run. This may be slower than what we were doing before, it depends on how many unification variables this cuts out.

@zilinc , can you try out my commit and see if it improves performance? If it doesn't, we may want to only do one pass to remove duplicates and then solve as normal.

**Comment by zilinc** [comment]
time goes down a lot: now 5.8s. (old 4.5, last commit 9)

**Comment by liamoc** [comment]
It's understandable that it might be slower because it's doing more work. I think an explicit graph presentation might be faster....

I do want to optimise this further but at least performance is OK now.

**Comment by zilinc** [comment]
The performance is acceptable, at least to me. The compiler time will be dominated by the FFI anyway so as long as it's not tooooo bad, ...

**Comment by liamoc** [comment]
dominated by FFI? why is that slow?

**Comment by zilinc** [comment]
The reason why I wanted to reduce the number of unif vars was to ease debugging...

**Comment by liamoc** [comment]
I think they should be drastically reduced.

**Comment by zilinc** [comment]
FFI is super slow because it goes through several monads (all the stages that we have in the compiler, from parsing to code-gen) to compiler each Cogent splice

**Comment by liamoc** [comment]
Ah I see, kind of unavoidable I guess.

**Comment by zilinc** [comment]
more numbers for bilby: 
 * old: 0m8.856s
 * new: 0m11.168s

**Comment by zilinc** [comment]
There doesn't seem to have significant impact in terms of performance at this stage, thus I close this ticket. If it becomes an issue, please reopen it.
