### ISSUE TITLE
Inconsistent syntax of type table?

### ISSUE THREAD

**Issue by gteege** [NICTA/cogent#376]
The format of the table generated by
  `cogent --table-c-types`
seems to be incompatible with the parser in `cogent/c-refinement/ReadTable.thy`.
This causes `_CorresSetup.thy` files to fail when run by isabelle.

**Comment by vjackson725** [comment]
Could you give an example of a failing type-table? Also, are you using dargent or not?

**Comment by gteege** [comment]
When preparing the example I found the reason: Caused by the change to the new cabal I was stuck with a Cogent binary from an old version. Using that together with the new Cogent distribution caused the inconsistency. After cleaning that up everything runs smoothly. Sorry for the inconvenience.
