### ISSUE TITLE
Makefile for cogent compiler should keep sandbox

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#42]
installing deps takes ages, so if possible we'd like to keep the sandbox (even in `make clean` maybe), unless it's terribly broken. I propose a `realclean` target, and should be used with caution.

**Comment by ajaysusarla** [comment]
@zilinc that makes sense. Also, use `make dev` to build/install in a sandbox.

**Comment by zilinc** [comment]
fixed by #93
