### ISSUE TITLE
`Drop var` constraint not solved

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#47]
To compile
```
type RbtConsumeF k v acc obsv = RbtElemAO k v acc obsv -> acc
type RbtCondF k v acc obsv = (RbtElemAO k v acc obsv)! -> Bool

rbtFTrue: all(k:< DS, v :<DS, acc, obsv). RbtCondF k v acc obsv
rbtFTrue _ = True
```
I got:
```
Leftover constraint!
Drop acc
   in the 1st alternative _
   in the definition at ("rbt.cogent" (line 91, column 1))
   for the function rbtFTrue
Leftover constraint!
Drop obsv
   in the 1st alternative _
   in the definition at ("rbt.cogent" (line 91, column 1))
   for the function rbtFTrue
```
I don't think it's the same bug as #29, as type arguments are applied while calling `rbtFTrue`.

**Comment by liamoc** [comment]
Can you post a full example? I tried to compile this file:

    type RbtElemAO k v acc obsv
    type RbtConsumeF k v acc obsv = RbtElemAO k v acc obsv -> acc
    type RbtCondF k v acc obsv = (RbtElemAO k v acc obsv)! -> Bool

    rbtFTrue: all(k:< DS, v :<DS, acc, obsv). RbtCondF k v acc obsv
    rbtFTrue _ = True

And it worked fine.
