### ISSUE TITLE
Error message when C variables are surrounded by $exp

### ISSUE THREAD

**Issue by azreika** [NICTA/cogent#52]
For antiQ C code like the following:
```
$ty:(Foo) foo;
foo->item = 12;
$exp:(some_cogent_function(foo));
```
The compiler returns the error message:
`cogent: desugarExpr (Error): the 'impossible' happened!`

The actual error is that foo is actually a variable in C, but surrounding the argument by `$exp` as well makes the compiler treat it as a Cogent variable, where it is undefined.

**Comment by zilinc** [comment]
It's because of `suppressError` in the typechecker. When pattern match on the return value of `tc`, we should compare if the log has anything in it, instead of `Left` or `Right`.
The patch is mostly ready, doing some tests now.
