### ISSUE TITLE
type well-formedness not checked

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#59]
they're mostly the passing tests that should fail as in ff23824.
where is the best place to check?

**Comment by zilinc** [comment]
There're more things like applying `#` to a non-record or non-abstract type. Should it also be an error or no-op? In the old compiler it was an error.
More generally, whether applying a type operator (e.g. `take`, `put`, `!`, `#`) to some non-sensical types should be an error or simply no-op?

**Comment by liamoc** [comment]
My inclination is to make it a no-op simply because it's a lot easier to implement. Right now type simplifier can't generate constraint solving errors.

**Comment by zilinc** [comment]
One exception might be `#`. It's an approximation of how the object is allocated: `#` means stack alloc and otherwise heap. But our variant types are always on the stack for ? reason. Allowing it wrongly implies that the user has control over it.

**Comment by liamoc** [comment]
I think it's OK to make it a no-op. When we switch to region types, the whole boxed/unboxed thing will become much much more transparent to the user.

**Comment by ajaysusarla** [comment]
Sorry to interrupt with the conversation with an orthogonal question. @liamoc What do you mean by:

> When we switch to region types, the whole boxed/unboxed thing will become much much more transparent to the user.

**Comment by liamoc** [comment]
We will have pointer types in region typed cogent. Pointers are tagged with a region. You can't freely dereference pointers. You can only dereference pointers to structs to get at their fields (using take/put as you do now).

So a boxed record type will just become a pointer to an unboxed record type. Similarly an abstract type will always be considered unboxed and you'll just pass pointers to them if you want them boxed.

**Comment by liamoc** [comment]
This moves the special handling of pointers into a dedicated type, which is much cleaner than our current approach that has to handle pointer problems for records and abstract types separately.

**Comment by ajaysusarla** [comment]
Nice!! Thanks for the explanation @liamoc
