### ISSUE TITLE
include <> syntax highlight

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#64]

**Comment by ajaysusarla** [comment]
@zilinc is this in `DocGent.hs`?

**Comment by liamoc** [comment]
Unlikely. DocGent uses the same colorised pretty printing as the rest of the compiler. PrettyPrint.hs includes that.

The editor syntax highlighting plugins are a separate thing again.

**Comment by ajaysusarla** [comment]
Ah! Makes sense. Thanks @liamoc
