### ISSUE TITLE
Update vfat and ext2fs implementations to build/run against the latest kernel

### ISSUE THREAD

**Issue by ajaysusarla** [NICTA/cogent#65]
Our implementation of both `ext2` and `vfat` in Cogent is a little dated, and we need to update it to build against the latest kernel implementation. 
Currently, it works against the patched 4.3 kernel in `Debian`, but doesn't build on the `Arch`'s kernel.

**Comment by zilinc** [comment]
should be enabled by b7fc6240de0aaaf39e25ccc451c5b6369c24cf2c

**Comment by ajaysusarla** [comment]
@zilinc That's awesome. I shall send the patches soon.
