### ISSUE TITLE
Widen unresolved

### ISSUE THREAD

**Issue by zilinc** [NICTA/cogent#9]
```
type X = <A U8 | B Bool>

f : () -> X
f _ = if True then widen (A 3) else widen (B False)
```
ends up with error message
```
Leftover constraint!
< > :<~ ?0 :& < A U8 > :<~ ?0
   in the definition at ("./test.cogent" (line 3, column 1))
   for the function f
   in the 1st alternative (_)
   when checking that the expression at ("./test.cogent" (line 4, column 7))
      if True then widen (A 3) else widen (B False)
   has type
      X
   in the then branch
   when checking the expression at ("./test.cogent" (line 4, column 20))
Leftover constraint!
< > :<~ ?2 :& < B Bool > :<~ ?2
   in the definition at ("./test.cogent" (line 3, column 1))
   for the function f
   in the 1st alternative (_)
   when checking that the expression at ("./test.cogent" (line 4, column 7))
      if True then widen (A 3) else widen (B False)
   has type
      X
   in the else branch
   when checking the expression at ("./test.cogent" (line 4, column 37))
```

**Comment by liamoc** [comment]
This is not a correct use of `widen`. The type given to <A 3> becomes ambiguous. Without widen, this example gives constraints like (slightly simplified): 

    <A U8> :<~ ?0
    <B Bool> :<~ ?0
    ?0 :< <A U8 | B Bool>

This resolves just fine. 

With widen, you get this instead:


     <A U8> :<~ ?0
     <B Bool> :<~ ?0
     ?0 :<~ <A U8 | B Bool>

And it's not able to determine `?0` without guessing.

In any event, the CDSL2.1 change will eliminate `widen` entirely. So this is not a huge issue.

**Comment by zilinc** [comment]
Yup, I didn't expect CDSL2.1 coming that soon. In that case, I'll just ignore it.
